[package]
name        = "normalizer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
symbolicator = { path = "../symbolicator" }
trace-core   = { path = "../trace-core" }
thiserror    = { workspace = true }
# Fast integer hashing for frame-address interning
rustc-hash   = "2"

[dev-dependencies]
tempfile = { workspace = true }
